[programs.devnet]
myepicproject = "69s61JXjofTGqs5GwpPm41WY2128MCKi2GzPeLRrExUh"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/naj44692/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js" 
